parameters:
#    miw_public.example.class: MIW\PublicBundle\Example

services:
#    miw_public.example:
#        class: %miw_public.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
     security.authentication.success_handler:
        class: MIW\PublicBundle\Security\LoginSuccessHandler
        arguments: [@router]
        tags:
            - { name: 'monolog.logger', channel: 'security' }