intranet_default_controller:
    resource: "@MIWIntranetBundle/Controller/DefaultController.php"
    type:     annotation
    
intranet_game_controller:
    resource: "@MIWIntranetBundle/Controller/GameController.php"
    type:     annotation
    
intranet_center_controller:
    resource: "@MIWIntranetBundle/Controller/CenterController.php"
    type:     annotation
    
intranet_myprofile_controller:
    resource: "@MIWIntranetBundle/Controller/MyProfileController.php"
    type:     annotation
    
intranet_sport_controller:
    resource: "@MIWIntranetBundle/Controller/SportController.php"
    type:     annotation