parameters:
#    miw_intranet.example.class: MIW\IntranetBundle\Example

services:
    geolocation_service:
        class: MIW\IntranetBundle\Services\GeolocationService
        arguments: [@service_container]
