parameters:
#    miw_intranet.example.class: MIW\IntranetBundle\Example

services:
#    miw_intranet.example:
#        class: %miw_intranet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
