imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    
# Framework Extra Configuration
sensio_framework_extra:
    router:   { annotations: true }
    request:  { converters: true }
    view:     { annotations: false }
    cache:    { annotations: true }
    security: { annotations: true }

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Doctrine configuration    
doctrine_mongodb:
    connections:
        default:
            server:   mongodb://localhost:27017
            options: {}
    default_database: weplay
    document_managers:
        default:
            auto_mapping: true
            
# Fos User configuration              
fos_user:
    db_driver: mongodb 
    firewall_name: main
    user_class: MIW\DataAccessBundle\Document\User
    registration:
        form:
            type:  fos_user_rest_registration
fos_rest:
    routing_loader:
        default_format: json
    view:
        view_response_listener: true
    param_fetcher_listener: true
        
sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.search_result:
            contexts: [admin]
        # Your other blocks
        
sonata_admin:
    title: WePlay Backend
    templates:
        layout:  MIWBackendBundle::standard_layout.html.twig
        user_block:          MIWBackendBundle:Core:user_block.html.twig
        
    dashboard:
        groups:
            acme.admin.group.content:
                label: Administración
                label_catalogue: AcmeDemoBundle
                items:
                    - miw_backend.admin.user
                    - miw_backend.admin.game
                    - miw_backend.admin.sport
                    - miw_backend.admin.center
                    
    
jms_serializer:
    metadata:
        file_cache:
            dir: "%kernel.cache_dir%/serializer"
        auto_detection: true
        directories:
            FOSUserBundle:
                namespace_prefix: "FOS\\UserBundle"
                path: "%kernel.root_dir%/config/serializer/fosuser"
                
lopi_pusher:
    app_id: 75199
    key: a559c43234e29ed6e683
    secret: 9abdf690d8f8b0da077d

    # Default configuration
    debug: true 
    host: http://api.pusherapp.com
    port: 80
    timeout: 30