miw_rest:
    resource: "@MIWRestBundle/Resources/config/routing.yml"
    prefix:   /api

miw_intranet:
    resource: "@MIWIntranetBundle/Resources/config/routing.yml"
    prefix:   /intranet

miw_public:
    resource: "@MIWPublicBundle/Resources/config/routing.yml"
    prefix:   /

miw_data_access:
    resource: "@MIWDataAccessBundle/Resources/config/routing.yml"
    prefix:   /

