miw_backend:
    resource: "@MIWBackendBundle/Resources/config/routing.yml"
    prefix:   /admin

miw_intranet:
    resource: "@MIWIntranetBundle/Resources/config/routing.yml"
    prefix:   /intranet

miw_public:
    resource: "@MIWPublicBundle/Resources/config/routing.yml"
    prefix:   /

miw_data_access:
    resource: "@MIWDataAccessBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
fos_user_security_login:
    pattern:  /
    defaults: { _controller: FOSUserBundle:Security:login }
        
fos_user_registration_register:
    pattern:  /registrarse
    defaults: { _controller: MIWPublicBundle:User:register }
    
cloud_rest:
    resource: "@MIWRestBundle/Controller/"
    prefix:   /api
    defaults: {_format: json}
    options:
        expose: true
        
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin