parameters:
#    miw_rest.example.class: MIW\RestBundle\Example

services:
#    miw_rest.example:
#        class: %miw_rest.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
